name: Tests

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    test-subscriber:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_subscribe

    test-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_publish
    
    test-unsubscribe:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_unsubscribe
    
    test-list-topics:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_list_topics

    test-get-topic-status:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_get_topic_status

    test-heartbeat:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_heartbeat

    test-cleanup-topic:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pip install pytest
            - run: |
                python src/server.py & 
                pytest src/test.py::test_cleanup_topic